services:
    db:
        image: mariadb:10.6
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql

    auth_service:
        build: ./auth_service
        restart: always
        depends_on:
            - db
        environment:
            MYSQL_HOST: ${MYSQL_HOST}
            MYSQL_PORT: ${MYSQL_PORT}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: auth_db
            JWT_SECRET: ${JWT_SECRET}

    project_service:
        build: ./project_service
        restart: always
        depends_on:
            - db
            - auth_service
        environment:
            MYSQL_HOST: ${MYSQL_HOST}
            MYSQL_PORT: ${MYSQL_PORT}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: project_db
            JWT_SECRET: ${JWT_SECRET}

    # board_service:
    #   build: ./board_service
    #   restart: always
    #   depends_on:
    #     - db
    #     - auth_service
    #   environment:
    #     MYSQL_HOST: ${MYSQL_HOST}
    #     MYSQL_PORT: ${MYSQL_PORT}
    #     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    #     MYSQL_DATABASE: board_db
    #     JWT_SECRET: ${JWT_SECRET}

    api_gateway:
        image: nginx:latest
        restart: always
        ports:
            - "8080:80" # Expose port 8080 ra host (user truy cập qua localhost:8080)
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro # Mount file config NGINX
        depends_on:
            - auth_service
            - project_service

volumes:
    db_data:
