services:
    db:
        image: mariadb:10.6
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        ports:
            - "3306:3306" # For debug
        volumes:
            - db_data:/var/lib/mysql
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 10s
            timeout: 5s
            retries: 5

    auth_service:
        build: ./auth_service
        restart: always
        depends_on:
            - db
        environment:
            MYSQL_HOST: ${MYSQL_HOST}
            MYSQL_PORT: ${MYSQL_PORT}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: auth_db
            JWT_SECRET: ${JWT_SECRET}
        volumes:
            - ./auth_service/migrations:/app/migrations
            - ./auth_service/app:/app/app
            - ./auth_service/tests:/app/tests
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    'python -c ''import urllib.request; urllib.request.urlopen("http://localhost:8000/docs")'' || exit 1',
                ]
            interval: 10s
            timeout: 5s
            retries: 5

    project_service:
        build: ./project_service
        restart: always
        depends_on:
            - db
            - auth_service
        environment:
            MYSQL_HOST: ${MYSQL_HOST}
            MYSQL_PORT: ${MYSQL_PORT}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: project_db
            JWT_SECRET: ${JWT_SECRET}
        volumes:
            - ./project_service/migrations:/app/migrations
            - ./project_service/app:/app/app
            - ./project_service/tests:/app/tests
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    'python -c ''import urllib.request; urllib.request.urlopen("http://localhost:8000/docs")'' || exit 1',
                ]
            interval: 10s
            timeout: 5s
            retries: 5

    board_service:
        build: ./board_service
        restart: always
        depends_on:
            - db
            - auth_service
            - project_service # To check project role
        environment:
            MYSQL_HOST: ${MYSQL_HOST}
            MYSQL_PORT: ${MYSQL_PORT}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: board_db
            JWT_SECRET: ${JWT_SECRET}
        volumes:
            - ./board_service/migrations:/app/migrations
            - ./board_service/app:/app/app
            - ./board_service/tests:/app/tests
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    'python -c ''import urllib.request; urllib.request.urlopen("http://localhost:8000/docs")'' || exit 1',
                ]
            interval: 10s
            timeout: 5s
            retries: 5

    api_gateway:
        image: nginx:latest
        restart: always
        ports:
            - "${API_GATEWAY_PORT}:80" # Expose port to host (default user access via localhost:8080)
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro # Mount file config NGINX
        depends_on:
            - auth_service
            - project_service
            - board_service

volumes:
    db_data:
