#!/bin/bash
set -e

mysql -uroot -p"$MYSQL_ROOT_PASSWORD" <<-EOSQL
    CREATE DATABASE IF NOT EXISTS ${AUTH_DATABASE};
    CREATE USER IF NOT EXISTS '${AUTH_USER}'@'%' IDENTIFIED BY '${AUTH_PASSWORD}';
    GRANT ALL PRIVILEGES ON ${AUTH_DATABASE}.* TO '${AUTH_USER}'@'%';

    CREATE DATABASE IF NOT EXISTS ${PROJECT_DATABASE};
    CREATE USER IF NOT EXISTS '${PROJECT_USER}'@'%' IDENTIFIED BY '${PROJECT_PASSWORD}';
    GRANT ALL PRIVILEGES ON ${PROJECT_DATABASE}.* TO '${PROJECT_USER}'@'%';

    CREATE DATABASE IF NOT EXISTS ${BOARD_DATABASE};
    CREATE USER IF NOT EXISTS '${BOARD_USER}'@'%' IDENTIFIED BY '${BOARD_PASSWORD}';
    GRANT ALL PRIVILEGES ON ${BOARD_DATABASE}.* TO '${BOARD_USER}'@'%';

    CREATE DATABASE IF NOT EXISTS ${COMMENT_DATABASE};
    CREATE USER IF NOT EXISTS '${COMMENT_USER}'@'%' IDENTIFIED BY '${COMMENT_PASSWORD}';
    GRANT ALL PRIVILEGES ON ${COMMENT_DATABASE}.* TO '${COMMENT_USER}'@'%';

    FLUSH PRIVILEGES;
EOSQL
